name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: install pnpm
        run: npm i -g pnpm

      - name: install deps
        run: pnpm i

      - name: build
        run: pnpm build
        env:
          BASE_PATH: beryllium-tech.github.io

      - name: create .nojekyll
        run: touch .output/public/.nojekyll

      - name: deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: .output/public
